import random
from typing import Callable

import tensorflow as tf


def load_random_model() -> (Callable, tf.keras.Model, str, int):
    models = [
        [tf.keras.applications.densenet.preprocess_input,
         tf.keras.applications.DenseNet121, 'DenseNet121', 224],
        [tf.keras.applications.densenet.preprocess_input,
         tf.keras.applications.DenseNet169, 'DenseNet169', 224],
        [tf.keras.applications.densenet.preprocess_input,
         tf.keras.applications.DenseNet201, 'DenseNet201', 224],
        [tf.keras.applications.densenet.preprocess_input,
         tf.keras.applications.EfficientNetB0, 'EfficientNetB0', 300],
        [tf.keras.applications.densenet.preprocess_input,
         tf.keras.applications.EfficientNetB1, 'EfficientNetB1', 300],
        [tf.keras.applications.densenet.preprocess_input,
         tf.keras.applications.EfficientNetB2, 'EfficientNetB2', 456],
        [tf.keras.applications.densenet.preprocess_input,
         tf.keras.applications.EfficientNetB3, 'EfficientNetB3', 456],
        [tf.keras.applications.densenet.preprocess_input,
         tf.keras.applications.EfficientNetB4, 'EfficientNetB4', 456],
        [tf.keras.applications.densenet.preprocess_input,
         tf.keras.applications.EfficientNetB5, 'EfficientNetB5', 456],
        [tf.keras.applications.densenet.preprocess_input,
         tf.keras.applications.EfficientNetB6, 'EfficientNetB6', 600],
        [tf.keras.applications.densenet.preprocess_input,
         tf.keras.applications.EfficientNetB7, 'EfficientNetB7', 600],
        [tf.keras.applications.inception_resnet_v2.preprocess_input,
         tf.keras.applications.InceptionResNetV2, 'InceptionResNetV2', 299],
        [tf.keras.applications.inception_v3.preprocess_input,
         tf.keras.applications.InceptionV3, 'InceptionV3', 299],
        [tf.keras.applications.mobilenet.preprocess_input,
         tf.keras.applications.MobileNet, 'MobileNet', 224],
        [tf.keras.applications.mobilenet_v2.preprocess_input,
         tf.keras.applications.MobileNetV2, 'MobileNetV2', 224],
        [tf.keras.applications.mobilenet_v3.preprocess_input,
         tf.keras.applications.MobileNetV3Large, 'MobileNetV3Large', 224],
        [tf.keras.applications.mobilenet_v3.preprocess_input,
         tf.keras.applications.MobileNetV3Small, 'MobileNetV3Small', 224],
        [tf.keras.applications.nasnet.preprocess_input,
         tf.keras.applications.NASNetLarge, 'NASNetLarge', 331],
        [tf.keras.applications.nasnet.preprocess_input,
         tf.keras.applications.NASNetMobile, 'NASNetMobile', 224],
        [tf.keras.applications.resnet.preprocess_input,
         tf.keras.applications.ResNet101, 'ResNet101', 224],
        [tf.keras.applications.resnet_v2.preprocess_input,
         tf.keras.applications.ResNet101V2, 'ResNet101V2', 224],
        [tf.keras.applications.resnet.preprocess_input,
         tf.keras.applications.ResNet152, 'ResNet152', 224],
        [tf.keras.applications.resnet_v2.preprocess_input,
         tf.keras.applications.ResNet152V2, 'ResNet152V2', 224],
        [tf.keras.applications.resnet.preprocess_input,
         tf.keras.applications.ResNet50, 'ResNet50', 224],
        [tf.keras.applications.resnet_v2.preprocess_input,
         tf.keras.applications.ResNet50V2, 'ResNet50V2', 224],
        [tf.keras.applications.vgg16.preprocess_input,
         tf.keras.applications.VGG16, 'VGG16', 224],
        [tf.keras.applications.vgg19.preprocess_input,
         tf.keras.applications.VGG19, 'VGG19', 224],
    ]
    prepocess_func, model_func, model_name, resolution = random.choice(models)
    model: tf.keras.Model = model_func()
    return prepocess_func, model, model_name, resolution
